# Example Custom Endpoints Configuration
#
# This file demonstrates how to define custom endpoints for the Helios Engine server.
# Custom endpoints allow you to expose additional HTTP routes alongside the OpenAI-compatible API.
#
# Save this file and use it with: helios-engine serve --custom-endpoints custom_endpoints.toml

[[endpoints]]
method = "GET"
path = "/api/version"
response = { version = "0.2.8", service = "Helios Engine" }
status_code = 200

[[endpoints]]
method = "GET"
path = "/api/status"
response = { status = "operational", uptime = "unknown" }
status_code = 200

[[endpoints]]
method = "POST"
path = "/api/echo"
response = { message = "Echo endpoint", note = "This returns static data" }
status_code = 200

[[endpoints]]
method = "GET"
path = "/api/config"
response = { model = "configurable", features = ["chat", "tools", "streaming"] }
status_code = 200

# You can add more endpoints as needed
# Supported HTTP methods: GET, POST, PUT, DELETE, PATCH
